Update ci-security-pipeline.yml

diff --git a/.github/workflows/ci-security-pipeline.yml b/.github/workflows/ci-security-pipeline.yml
--- a/.github/workflows/ci-security-pipeline.yml
+++ b/.github/workflows/ci-security-pipeline.yml
@@ -42,18 +42,18 @@ jobs:
         run: |
           REPORT_PATH="dependency-check-report/dependency-check-report.csv"
           if [ -f "$REPORT_PATH" ]; then
-            if grep -q -E "CRITICAL|HIGH|MEDIUM" "$REPORT_PATH"; then
-              echo "SCA: Vulnerabilities found! Failing pipeline."
-              echo "---- Vulnerabilities detected ----"
-              awk -F',' '{gsub(/"/,"",$2); gsub(/"/,"",$3); if($3 ~ /CRITICAL|HIGH|MEDIUM/) print $3, $2}' "$REPORT_PATH"
-              echo "----------------------------------"
-              exit 1
-            else
-              echo "No vulnerabilities found."
-            fi
+          if grep -q -E "CRITICAL|HIGH|MEDIUM" "$REPORT_PATH"; then
+          echo "SCA: Vulnerabilities found! Failing pipeline."
+          echo "---- Vulnerabilities detected ----"
+          awk -F',' '{gsub(/"/,"",$2); gsub(/"/,"",$3); if($3 ~ /CRITICAL|HIGH|MEDIUM/) print $3, $2}' "$REPORT_PATH"
+          echo "----------------------------------"
+          exit 1
           else
-            echo "Report file not found!"
-            exit 1
+          echo "No vulnerabilities found."
+          fi
+          else
+          echo "Report file not found!"
+          exit 1
           fi
 
       # --- Build Docker image ---
